begin;

-- Creates the table if it does not exist, and adds any missing columns when it does.
-- PostgreSQL cannot physically reorder columns on an existing table with ALTER TABLE,
-- so the view at the end exposes the exact form order requested.

create table if not exists public.sugarcane_monitoring (
  id bigint generated by default as identity primary key,
  field_id text,
  block_id text,
  area double precision,
  irrigation_type text,
  water_source text,
  tam_mm text,
  soil_type text,
  soil_ph double precision,
  field_remarks text,
  geom_polygon jsonb,
  trial_number text,
  trial_name text,
  contact_person text,
  date_recorded timestamptz not null default now(),
  crop_type text,
  crop_class text,
  planting_date timestamptz,
  previous_cutting timestamptz,
  expected_harvest_date timestamptz,
  residue_type text,
  residue_management_method text,
  residual_management_remarks text,
  fertilizer_type text,
  nutrient_application_date timestamptz,
  application_rate double precision,
  fertilizer_applications jsonb,
  foliar_sampling_date timestamptz,
  herbicide_name text,
  weed_application_date timestamptz,
  weed_application_rate double precision,
  herbicide_applications jsonb,
  pest_remarks text,
  disease_remarks text,
  harvest_date timestamptz,
  harvest_yield double precision,
  quality_remarks text,
  well_known_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sugarcane_monitoring
  add column if not exists field_id text,
  add column if not exists block_id text,
  add column if not exists area double precision,
  add column if not exists irrigation_type text,
  add column if not exists water_source text,
  add column if not exists tam_mm text,
  add column if not exists soil_type text,
  add column if not exists soil_ph double precision,
  add column if not exists field_remarks text,
  add column if not exists geom_polygon jsonb,
  add column if not exists trial_number text,
  add column if not exists trial_name text,
  add column if not exists contact_person text,
  add column if not exists date_recorded timestamptz not null default now(),
  add column if not exists crop_type text,
  add column if not exists crop_class text,
  add column if not exists planting_date timestamptz,
  add column if not exists previous_cutting timestamptz,
  add column if not exists expected_harvest_date timestamptz,
  add column if not exists residue_type text,
  add column if not exists residue_management_method text,
  add column if not exists residual_management_remarks text,
  add column if not exists fertilizer_type text,
  add column if not exists nutrient_application_date timestamptz,
  add column if not exists application_rate double precision,
  add column if not exists fertilizer_applications jsonb,
  add column if not exists foliar_sampling_date timestamptz,
  add column if not exists herbicide_name text,
  add column if not exists weed_application_date timestamptz,
  add column if not exists weed_application_rate double precision,
  add column if not exists herbicide_applications jsonb,
  add column if not exists pest_remarks text,
  add column if not exists disease_remarks text,
  add column if not exists harvest_date timestamptz,
  add column if not exists harvest_yield double precision,
  add column if not exists quality_remarks text,
  add column if not exists well_known_text text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists sugarcane_monitoring_date_recorded_idx
  on public.sugarcane_monitoring (date_recorded desc);

create index if not exists sugarcane_monitoring_block_id_idx
  on public.sugarcane_monitoring (block_id);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'sugarcane_monitoring'
      and column_name = 'trial_number'
      and data_type <> 'text'
  ) then
    alter table public.sugarcane_monitoring
      alter column trial_number type text
      using nullif(trial_number::text, '');
  end if;
end $$;

create or replace function public.set_sugarcane_monitoring_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_sugarcane_monitoring_updated_at
on public.sugarcane_monitoring;

create trigger trg_sugarcane_monitoring_updated_at
before update on public.sugarcane_monitoring
for each row
execute function public.set_sugarcane_monitoring_updated_at();

create or replace view public.sugarcane_monitoring_form_order as
select
  field_id,
  block_id,
  area,
  irrigation_type,
  water_source,
  tam_mm,
  soil_type,
  soil_ph,
  field_remarks,
  geom_polygon,
  trial_number,
  trial_name,
  contact_person,
  date_recorded,
  crop_type,
  crop_class,
  planting_date,
  previous_cutting,
  expected_harvest_date,
  residue_type,
  residue_management_method,
  residual_management_remarks,
  fertilizer_type,
  nutrient_application_date,
  application_rate,
  fertilizer_applications,
  foliar_sampling_date,
  herbicide_name,
  weed_application_date,
  weed_application_rate,
  herbicide_applications,
  pest_remarks,
  disease_remarks,
  harvest_date,
  harvest_yield,
  quality_remarks,
  well_known_text
from public.sugarcane_monitoring;

commit;
